### ISSUE TITLE
Webmin Tomcat Plugin Java Not Found

### ISSUE THREAD

**Issue by avaramis** [AcuGIS/OpenNameSearch#12]
Hi I was/am excitied to use your Tomcat plugin as it will hopefully enable me to restart tomcat from my phone if things go wrong while prototyping.
The setup is incomplete stating that:
Warning: Java is not found. Install it manually or from the Java tab
![image](https://user-images.githubusercontent.com/12189363/74668669-b2bc5f80-5173-11ea-8014-682ba5a19257.png)
When I follow the link to the "java tab" I have:
```
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.941 Date: Mon, 17 Feb 2020 15:53:50 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

open:No such file or directory at ./java-lib.pl line 118. 
```
I can take a shot at installing Java manually but pushbutton maintenance is nice for somebody as time constrained as myself.

This is a really great idea thanks for making it :)

**Comment by DavidGhedini** [comment]
Checking now....

**Comment by DavidGhedini** [comment]
Can you please move this to the Webmin Tomcat Module?  For some reason you opened it under OpenNameSearch.

**Comment by DavidGhedini** [comment]
https://github.com/cited/Tomcat-Webmin-Module

**Comment by avaramis** [comment]
Moved it
