### ISSUE TITLE
Getting osm2pgsql directory is empty on a fresh install

### ISSUE THREAD

**Issue by leonleslie** [AcuGIS/OpenNameSearch#19]
After a refresh install of Ubuntu 22.04 I get the following error

CMake Error at CMakeLists.txt:60 (message):
  The osm2pgsql directory is empty.  Did you forget to check out Nominatim
  recursively?

  Try updating submodules with: git submodule update --init

-- Configuring incomplete, errors occurred!
See also "/home/ntim/Nominatim/build/CMakeFiles/CMakeOutput.log".

**Comment by kaloyan13** [comment]
Try [01e69a3](https://github.com/AcuGIS/Nominatim-Server/commit/01e69a3f620a1c1fb2d57db4d94517981b43a81d)

**Comment by leonleslie** [comment]
It works like a charm! Much appreciation
