### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by Livitin** [AcuGIS/OpenNameSearch#20]
Try to install on clean Ubuntu 24.04 LTS.
Get this break error:
....
Adding debian:vTrus_Root_CA.pem
Adding debian:XRamp_Global_CA_Root.pem
done.
Setting up default-jre-headless (2:1.21-75+exp1) ...
Setting up osmosis (0.49.2-2) ...
Processing triggers for php8.3-cli (8.3.6-0ubuntu0.24.04.3) ...
Processing triggers for php8.3-cgi (8.3.6-0ubuntu0.24.04.3) ...
Processing triggers for libapache2-mod-php8.3 (8.3.6-0ubuntu0.24.04.3) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**It seems to me the problem in script in function install_prerequisites** ->  **pip3 install psycopg** :
function install_prerequisites(){
    apt-get install -y build-essential cmake g++ libboost-dev libboost-system-dev \
        libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev\
        libbz2-dev libpq-dev liblua5.3-dev lua5.3 libgeos-dev libgeos++-dev libproj-dev \
        postgresql-server-dev-${PG_VER} postgresql-${PG_VER}-postgis-${PGIS_VER} postgresql-contrib-${PG_VER} \
        apache2 php php-{cgi,cli,intl,pgsql,pear,db} libapache2-mod-php \
                                libicu-dev python3-{dotenv,psycopg2,psutil,jinja2,icu,datrie,sqlalchemy,asyncpg,pip,pyosmium} \
        git osmosis libboost-python-dev nlohmann-json3-dev

                pip3 install psycopg
}

**Comment by DavidGhedini** [comment]
This hasn't been updated for Ubuntu 24 yet.  As of Ubuntu 24 you need to use virtualenv.

virtualenv --python=/usr/bin/python3 --system-site-packages .venv
source .venv/bin/activate
pip3 install psycopg

**Comment by Livitin** [comment]
I replaced _pip3 install psycopg_ with new strings, but got error: _./Nominatim-Server.sh: line 79: virtualenv: command not found_

**Comment by Livitin** [comment]
Next error: ./Nominatim-Server.sh: line 135: unzip: command not found

**Comment by DavidGhedini** [comment]
We'll be updating this for Ubuntu 24 later today. We'll add comment here so you'll be notified.

**Comment by Livitin** [comment]
Here is my variant:
_apt update_
_wget https://raw.githubusercontent.com/AcuGIS/Nominatim-Server/master/Nominatim-Server.sh_
_chmod 755 Nominatim-Server.sh_
_apt install -y python3-virtualenv_ **don't know do i really need this...**
_apt install -y unzip python3-psycopg_
_vi Nominatim-Server.sh_ **change postgresql version to 16** 
_./Nominatim-Server.sh https://download.geofabrik.de/russia/south-fed-district-latest.osm.pbf_

**Comment by kaloyan13** [comment]
Use Ubuntu 24 script from 02407795eb5a45735c3f92032456f2c8f3c0f0db
