### ISSUE TITLE
Data last updated:  DB Error: no such table

### ISSUE THREAD

**Issue by jrischma** [AcuGIS/OpenNameSearch#3]
Hi, great work, but show this msg:

Data last updated: 
DB Error: no such table

what is the problem?

thanks

![image](https://user-images.githubusercontent.com/11020812/28279805-ae78bd82-6aef-11e7-8eaf-433c26e0de98.png)

**Comment by DavidGhedini** [comment]
Did you add the cron? What is the OS? Were there errors on install?

**Comment by jrischma** [comment]
NO cron, Ubuntu 14.04
