### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by jrischma** [AcuGIS/OpenNameSearch#4]
Hi, during install show this

![image](https://user-images.githubusercontent.com/11020812/28279883-ea25387e-6aef-11e7-94f2-eee0274d21f8.png)

this is a problem or is normal?

thanks

**Comment by DavidGhedini** [comment]
What is the OS and Resources (RAM, CPU, and Disk type and amount)?

**Comment by jrischma** [comment]
Ubuntu 14.04.5 64BIT
20 GB SSD
2GB RAM
2GB CPU

(digitalOcean)

thanks

**Comment by DavidGhedini** [comment]
What is the PBF you are trying to load?

**Comment by jrischma** [comment]
first try with http://download.geofabrik.de/south-america-latest.osm.pbf
second try with http://download.geofabrik.de/south-america/chile-latest.osm.pbf
third try with ./reload-OpenNameSearch.sh http://download.geofabrik.de/south-america/chile-latest.osm.pbf
for last time i receive

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Out of memory for dense node cache, reduce --cache size
Error occurred, cleaning up
ERROR: Error executing external command: /home/ntim/Nominatim-2.5.1/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 1698 -P 5432 -d nominatim /home/ntim/chile-latest.osm.pbf
Error executing external command: /home/ntim/Nominatim-2.5.1/osm2pgsql/osm2pgsql -lsc -O gazetteer --hstore --number-processes 1 -C 1698 -P 5432 -d nominatim /home/ntim/chile-latest.osm.pbf
[setup.log.txt](https://github.com/AcuGIS/OpenNameSearch/files/1153539/setup.log.txt)

**Comment by DavidGhedini** [comment]
I don't think you are going to get very far loading South America on a DO2.
Can you reload your box and try Washington, DC?

**Comment by jrischma** [comment]
my install finally work:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install unattended-upgrades
sudo apt-get -y install git

git clone https://github.com/AcuGIS/OpenNameSearch
cd OpenNameSearch
chmod 755 OpenNameSearch.sh
./OpenNameSearch.sh http://download.geofabrik.de/south-america/chile-latest.osm.pbf
chmod +x /etc/init.d/nominatim_updater

is necessary modify file settings/local.php

@define('CONST_Website_BaseURL', 'http://youDomain.com/nominatim/');

thanks

**Comment by DavidGhedini** [comment]
Great!
Thanks for sharing solution.
Best,
David

**Comment by jrischma** [comment]
thanks you! great script, good work!
edit: maybe is necessary show requirements minimum for server, i test with 512MB and 1GB ram but not work.
Edit2: do u have a script for install OSRM + Nominatim?
