### ISSUE TITLE
Error reload-OpenNameSearch.sh

### ISSUE THREAD

**Issue by jrischma** [AcuGIS/OpenNameSearch#5]
Hi again, on my first install use this packet http://download.geofabrik.de/south-america/chile-latest.osm.pbf

Now i use this command

./reload-OpenNameSearch.sh http://download.geofabrik.de/south-america/chile-latest.osm.pbf http://download.geofabrik.de/south-america/argentina-latest.osm.pbf http://download.geofabrik.de/south-america/bolivia-latest.osm.pbf http://download.geofabrik.de/south-america/brazil-latest.osm.pbf http://download.geofabrik.de/south-america/colombia-latest.osm.pbf http://download.geofabrik.de/south-america/ecuador-latest.osm.pbf http://download.geofabrik.de/south-america/paraguay-latest.osm.pbf http://download.geofabrik.de/south-america/peru-latest.osm.pbf http://download.geofabrik.de/south-america/suriname-latest.osm.pbf http://download.geofabrik.de/south-america/uruguay-latest.osm.pbf

![image](https://user-images.githubusercontent.com/11020812/28323019-a257a188-6ba5-11e7-809d-470939a519cc.png)

Ubuntu 14.04.5 x64
RAM 2GB
SSD 40GB

**Comment by DavidGhedini** [comment]
Hi -
Can you please limit issues to those that use small PBFs?
When you try to load that amount of data on a 2GB RAM VPS, the errors are not very meaningful.
Also, check df -h and see if your disk is filling up.
Thanks,
David

**Comment by jrischma** [comment]
this command work:

./reload-OpenNameSearch.sh http://download.geofabrik.de/south-america/chile-latest.osm.pbf

how can i add a country? 
for example argentina

if i execute :
./reload-OpenNameSearch.sh http://download.geofabrik.de/south-america/argentina-latest.osm.pbf
this command delete the first pbf installed (chile-latest.osm.pbf) ??

**Comment by DavidGhedini** [comment]
Yes, that is correct.
When you wish to add a new PBF, you need to reload both the new AND existing PBF.
This is because it drops the database (which is why your table is not being found, I think).
David

**Comment by DavidGhedini** [comment]
See line #13 below:
`#Merge multiple pbf files into one, so we can import into Nominatim`
`function merge_osm_maps(){`

**Comment by jrischma** [comment]
perfect, so first i will test if work for 2 pbf!

thanks
