### ISSUE TITLE
Ubuntu 16.04 Compatible Script

### ISSUE THREAD

**Issue by f1ana** [AcuGIS/OpenNameSearch#6]
Hello,

I've prepared an OpenNameSearch script that will work for Ubuntu 16.04.
It worked well for me and I'm wondering if it makes sense to merge this up into your project.
Here's the script:  https://github.com/f1ana/OpenNameSearch/blob/feature/ubuntu-16/OpenNameSearch-Ubuntu16.sh

-Chris

**Comment by DavidGhedini** [comment]
Hi Chris -
Sorry for the long delay.
Ill have a look and you can publish here if you wish to (or whatever you prefer).
Thanks,
David

**Comment by f1ana** [comment]
See PR #7

**Comment by DavidGhedini** [comment]
Hi Chris -
Thank you!
I have updated the README to reflect the addition.
Thanks again,
David
